name: ddo
version: 0.2.8
author: Nathan Kerr <nathankerr@gmail.com>
description: A port of PHP Data Objects to Dart.
homepage: https://github.com/TheBosZ/ddo-dart
dependencies:
  postgresql: '>=0.2.14 <0.3.0'
  sqljocky: '^0.14.1'
dev_dependencies:
  browser: any
  test: '^0.12.10'
environment:
  sdk: ">=1.8.0 <2.0.0"
